// Generated by delombok at Thu Apr 12 13:54:15 CEST 2018
package com.dokan.java.legacy.structure;

public final class FileData {
	private final byte[] bytes;
	private final int length;

	@SuppressWarnings("all")
	public FileData(final byte[] bytes, final int length) {
		this.bytes = bytes;
		this.length = length;
	}

	@SuppressWarnings("all")
	public byte[] getBytes() {
		return this.bytes;
	}

	@SuppressWarnings("all")
	public int getLength() {
		return this.length;
	}

	@Override
	@SuppressWarnings("all")
	public boolean equals(final Object o) {
		if (o == this) return true;
		if (!(o instanceof FileData)) return false;
		final FileData other = (FileData) o;
		if (!java.util.Arrays.equals(this.getBytes(), other.getBytes())) return false;
		if (this.getLength() != other.getLength()) return false;
		return true;
	}

	@Override
	@SuppressWarnings("all")
	public int hashCode() {
		final int PRIME = 59;
		int result = 1;
		result = result * PRIME + java.util.Arrays.hashCode(this.getBytes());
		result = result * PRIME + this.getLength();
		return result;
	}

	@Override
	@SuppressWarnings("all")
	public String toString() {
		return "FileData(bytes=" + java.util.Arrays.toString(this.getBytes()) + ", length=" + this.getLength() + ")";
	}
}
