/*
  JDokan : Java library for Dokan

  Copyright (C) 2008 Yu Kobayashi http://yukoba.accelart.jp/

  http://decas-dev.net/en

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU Lesser General Public License as published by the Free
Software Foundation; either version 3 of the License, or (at your option) any
later version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU Lesser General Public License along
with this program. If not, see <http://www.gnu.org/licenses/>.
*/

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_decasdev_dokan_Dokan */

#ifndef _Included_net_decasdev_dokan_Dokan
#define _Included_net_decasdev_dokan_Dokan
#ifdef __cplusplus
extern "C" {
#endif
#undef net_decasdev_dokan_Dokan_DOKAN_SUCCESS
#define net_decasdev_dokan_Dokan_DOKAN_SUCCESS 0L
#undef net_decasdev_dokan_Dokan_DOKAN_ERROR
#define net_decasdev_dokan_Dokan_DOKAN_ERROR -1L
#undef net_decasdev_dokan_Dokan_DOKAN_DRIVE_LETTER_ERROR
#define net_decasdev_dokan_Dokan_DOKAN_DRIVE_LETTER_ERROR -2L
#undef net_decasdev_dokan_Dokan_DOKAN_DRIVER_INSTALL_ERROR
#define net_decasdev_dokan_Dokan_DOKAN_DRIVER_INSTALL_ERROR -3L
#undef net_decasdev_dokan_Dokan_DOKAN_START_ERROR
#define net_decasdev_dokan_Dokan_DOKAN_START_ERROR -4L
#undef net_decasdev_dokan_Dokan_DOKAN_MOUNT_ERROR
#define net_decasdev_dokan_Dokan_DOKAN_MOUNT_ERROR -5L
/*
 * Class:     net_decasdev_dokan_Dokan
 * Method:    mount
 * Signature: (Lnet/decasdev/dokan/DokanOptions;Lnet/decasdev/dokan/DokanOperations;)I
 */
JNIEXPORT jint JNICALL Java_net_decasdev_dokan_Dokan_mount
  (JNIEnv *, jclass, jobject, jobject);

///*
// * Class:     net_decasdev_dokan_Dokan
// * Method:    unmount
// * Signature: (C)Z
// */
//JNIEXPORT jboolean JNICALL Java_net_decasdev_dokan_Dokan_unmount
//  (JNIEnv *, jclass, jchar);

/*
 * Class:     net_decasdev_dokan_Dokan
 * Method:    removeMountPoint
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_net_decasdev_dokan_Dokan_removeMountPoint
  (JNIEnv *env, jclass, jstring jMountPoint);

/*
 * Class:     net_decasdev_dokan_Dokan
 * Method:    isNameInExpression
 * Signature: (Ljava/lang/String;Ljava/lang/String;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_net_decasdev_dokan_Dokan_isNameInExpression
  (JNIEnv *, jclass, jstring, jstring, jboolean);

/*
 * Class:     net_decasdev_dokan_Dokan
 * Method:    getVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_decasdev_dokan_Dokan_getVersion
  (JNIEnv *, jclass);

/*
 * Class:     net_decasdev_dokan_Dokan
 * Method:    getDriverVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_decasdev_dokan_Dokan_getDriverVersion
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
